#!/bin/bash
say i am the scat man
say ski-bi dibby dib yo da dub dub
say yo da dub dub
say ski-bi dibby dib yo da dub dub
say yo da dub dub
say i am the scat man
say ski-bi dibby dib yo da dub dub
say yo da dub dub
say ski-bi dibby dib yo da dub dub

say Ba-da-ba-da-ba-be bop bop bodda bope
say Bop ba bodda bope
say Be bop ba bodda bope
say Bop ba bodda
say Ba-da-ba-da-ba-be bop ba bodda bope
say Bop ba bodda bope
say Be bop ba bodda bope
say Bop ba bodda bope

say ski-bi dibby dib yo da dub dub
say yo da dub dub
say ski-bi dibby dib yo da dub dub
say yo da dub dub
say ski-bi dibby dib yo da dub dub
say yo da dub dub
say ski-bi dibby dib yo da dub dub
