#!/bin/bash

VOICE=$1

say -v $VOICE i am the scat man
say -v $VOICE ski-bi dibby dib yo da dub dub
say -v $VOICE yo da dub dub
say -v $VOICE ski-bi dibby dib yo da dub dub
say -v $VOICE yo da dub dub
say -v $VOICE i am the scat man
say -v $VOICE ski-bi dibby dib yo da dub dub
say -v $VOICE yo da dub dub
say -v $VOICE ski-bi dibby dib yo da dub dub

say -v $VOICE Ba-da-ba-da-ba-be bop bop bodda bope
say -v $VOICE Bop ba bodda bope
say -v $VOICE Be bop ba bodda bope
say -v $VOICE Bop ba bodda
say -v $VOICE Ba-da-ba-da-ba-be bop ba bodda bope
say -v $VOICE Bop ba bodda bope
say -v $VOICE Be bop ba bodda bope
say -v $VOICE Bop ba bodda bope

say -v $VOICE ski-bi dibby dib yo da dub dub
say -v $VOICE yo da dub dub
say -v $VOICE ski-bi dibby dib yo da dub dub
say -v $VOICE yo da dub dub
say -v $VOICE ski-bi dibby dib yo da dub dub
say -v $VOICE yo da dub dub
say -v $VOICE ski-bi dibby dib yo da dub dub
