#!/bin/bash

VOICE="$1"

if [ -z $VOICE ]
then
    echo "The default voice is nice, but did you know others exist?"
    echo "Here's the list..."
    say -v '?'
fi

function sayWithVoice {
    if [ -z $VOICE ]
    then
	say $@
    else
	say -v $VOICE $@
    fi
}

sayWithVoice i am the scat man
sayWithVoice ski-bi dibby dib yo da dub dub
sayWithVoice yo da dub dub
sayWithVoice ski-bi dibby dib yo da dub dub
sayWithVoice yo da dub dub
sayWithVoice i am the scat man
sayWithVoice ski-bi dibby dib yo da dub dub
sayWithVoice yo da dub dub
sayWithVoice ski-bi dibby dib yo da dub dub

sayWithVoice Ba-da-ba-da-ba-be bop bop bodda bope
sayWithVoice Bop ba bodda bope
sayWithVoice Be bop ba bodda bope
sayWithVoice Bop ba bodda
sayWithVoice Ba-da-ba-da-ba-be bop ba bodda bope
sayWithVoice Bop ba bodda bope
sayWithVoice Be bop ba bodda bope
sayWithVoice Bop ba bodda bope

sayWithVoice ski-bi dibby dib yo da dub dub
sayWithVoice yo da dub dub
sayWithVoice ski-bi dibby dib yo da dub dub
sayWithVoice yo da dub dub
sayWithVoice ski-bi dibby dib yo da dub dub
sayWithVoice yo da dub dub
sayWithVoice ski-bi dibby dib yo da dub dub
